### ISSUE TITLE
Is it okay to skip the "Format" section of ATACseq_workflow.txt ?

### ISSUE THREAD

**Issue by rrashford** [reskejak/ATAC-seq#10]
Hello! Thanks so much for this paper, it's proven very helpful in my own work.

As I've tried to work through the ATACseq_workflow.txt commands, I get stuck at trying to run the bash scripts. They aren't recognizing the fixed bam file that I created from the lines above. It's saying that my .bedpe isn't being recognized, although when I run the command to see the header of the file there is definitely something there. Is there something I'm missing or should be adding to the .sh script to make it recognize the .bedpe file? My error from the terminal is copy and pasted below.

Alternatively, I tried seeing if I could go through the rest of the analysis through [Galaxy](https://usegalaxy.org/) by skipping the fixing, Tn5 shifting, and minimal conversion to test if things would even run without this formatting step. I was able to go through all of the differential analysis without errors. But I'm wondering: are these formatting steps very necessary for normalization and differential analysis of ATAC-seq datasets, or would I be able to interpret differential analysis (I subsampled by counts on sorted bam files, then ran MACS2 to get peaks, then normalized and performed DA with TMM and edgeR respectively) correctly without that step?

Any advice or help would be greatly appreciated!!

`$ bash bedpeTn5shift.sh fELSadultBBrep1_fixed.bedpe > fELS_adultBBrep1.tn5.bedpe `
` 'for reading (No such file or directory) ' fELSadultBBrep1_fixed.bedpe `
`$ head fELSadultBBrep1_fixed.bedpe `
`chr5    125518595       125518654       chr5    125518778       125518837       A00741:283:HNWHNDRXY:1:1101:1407:33458 42                                                  +-
chr3    83872740        83872799        chr3    83872763        83872822        A00741:283:HNWHNDRXY:1:1101:1931:32769 42                                                  +-
chr16   31007545        31007604        chr16   31007668        31007727        A00741:283:HNWHNDRXY:1:1101:2003:33113 42                                                  +-
chr7    25088905        25088964        chr7    25089185        25089244        A00741:283:HNWHNDRXY:1:1101:2013:15937 42                                                  +-
chr11   78201778        78201837        chr11   78202117        78202176        A00741:283:HNWHNDRXY:1:1101:2040:28980 42                                                  +-
chr11   81687086        81687145        chr11   81687109        81687168        A00741:283:HNWHNDRXY:1:1101:2157:9612  42                                                  +-
chr8    107757780       107757839       chr8    107757932       107757991       A00741:283:HNWHNDRXY:1:1101:2483:33818 42                                                  +-
chr9    3006777 3006836 chr9    3006792 3006851 A00741:283:HNWHNDRXY:1:1101:2501:15906  1       +       -
chr8    37451034        37451093        chr8    37451053        37451112        A00741:283:HNWHNDRXY:1:1101:2564:16235 42                                                  +-
chr11   74187762        74187821        chr11   74187780        74187839        A00741:283:HNWHNDRXY:1:1101:2573:20979 31                                                  +- `

**Comment by reskejak** [comment]
That seems like a strange error. You could try supplying absolute paths to the command, rather than just the file name, to see if that helps the machine locate it.

To answer your other question: yes, skipping these steps should marginally affect the resulting analysis. Tn5 shifting is more of a historical formality and may only noticeably impact TF/regulator footprinting analysis. In old days, MACS2 could *only* accept BEDPE files in this minimal format. Newer versions of MACS are now able to accept other formats.

If you still want to try Tn5 shifting to see if that impacts your data, I would try doing that operation directly on the BAM file (shifting read coordinates, there are tools for this) then supplying BAMPE to MACS/csaw etc. for peak calling and differential analysis.

Hope this helps!

**Comment by rrashford** [comment]
Ah, I see! This was very helpful, thank you.

I ended up supplying my BAM files directly to MACS2 (through Galaxy) and using the extension and shift size parameters to account for the Tn5 shifting, which I think solves the issue when trying to use my peak regions for downstream TF/regulator footprinting analysis.

Thanks again!
