### ISSUE TITLE
species of example

### ISSUE THREAD

**Issue by Rfriedmancolumbia** [reskejak/ATAC-seq#11]
Jake,
I am working through the ATACSeq workflow in your "ATAC-Seq" normalization paper. The ATACseq example is for a mouse dataset, which from context should be from the ARIDIA paper GSE121198. However the only ATACSeq dataset in GSE121198  is a human dataset. 
Is there a way that I can get the mouse fastqc files that you analyzed in your paper, so that I may use it to work through your protocol?

Thanks and best wishes,
Rich
Richard Friedman
Biomedical Informatics Shared Resource,
Herbert Irving Comprehensive Cancer Center
Columbia University Irving Medical Center

**Comment by reskejak** [comment]
Hi Rich,

Sorry for the delay. The mouse ATAC-seq data are indeed located in the GSE superseries you listed (GSE121198). Here is the specific Mouse_ATAC repository: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE129783

**Comment by Rfriedmancolumbia** [comment]
Jake,

Thank you for the link.

Best wishes,
Rich

________________________________
From: Jake Reske ***@***.***>
Sent: Monday, December 9, 2024 8:00 PM
To: reskejak/ATAC-seq ***@***.***>
Cc: Friedman, Richard A. ***@***.***>; State change ***@***.***>
Subject: [EXTERNAL] Re: [reskejak/ATAC-seq] species of example (Issue #11)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Hi Rich,

Sorry for the delay. The mouse ATAC-seq data are indeed located in the GSE superseries you listed (GSE121198). Here is the specific Mouse_ATAC repository: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE129783
