### ISSUE TITLE
availability of mouse ATACSeq data

### ISSUE THREAD

**Issue by Rfriedmancolumbia** [reskejak/ATAC-seq#12]
Jake,
I am working through the ATACSeq workflow in your "ATAC-Seq" normalization paper. The ATACseq example is for a mouse dataset, which from context should be from the ARIDIA paper GSE121198. However the only ATACSeq dataset in GSE121198 is a human dataset.
Is there a way that I can get the mouse fastqc files that you analyzed in your paper, so that I may use it to work through your protocol?

Thanks and best wishes,
Rich
Richard Friedman
Biomedical Informatics Shared Resource,
Herbert Irving Comprehensive Cancer Center
Columbia University Irving Medical Center

**Comment by reskejak** [comment]
Hi Rich,

You are looking for the mouse ATAC-seq experiment, GSE129783, within SuperSeries GSE121198. Those samples can be found here: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE129783

Best,
Jake

**Comment by Rfriedmancolumbia** [comment]
Jake,

Thank you. I also see why I missed it earlier.
I didn;t click "more". My fault.

Best wishes,
Rich
________________________________
From: Jake Reske ***@***.***>
Sent: Wednesday, September 28, 2022 9:05 AM
To: reskejak/ATAC-seq ***@***.***>
Cc: Friedman, Richard A. ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [reskejak/ATAC-seq] availability of mouse ATACSeq data (Issue #12)


Hi Rich,

You are looking for the mouse ATAC-seq experiment, GSE129783, within SuperSeries GSE121198. Those samples can be found here: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE129783<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2Fgeo%2Fquery%2Facc.cgi%3Facc%3DGSE129783&data=05%7C01%7Craf4%40cumc.columbia.edu%7C10490266f2f04c92113408daa15242b5%7Cb0002a9b0017404d97dc3d3bab09be81%7C1%7C0%7C637999671920903497%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=WXAjwiywN8CVnLmXWdNh5%2F9yR4vKBybBqxJBA0gH4Cw%3D&reserved=0>

Best,
Jake
