### ISSUE TITLE
Input object type into regionCounts() ?

### ISSUE THREAD

**Issue by rrashford** [reskejak/ATAC-seq#4]
Hello,

Thank you so much for this script. When I get to the link that establishes the " peak.counts " variable like so: 
`peak.counts <- regionCounts(pe.bams, all.peaks, param=param) `

I get the following error:
**Error in .extractPE(bam.file, where = where, param = param) : 
  failed to open BAM index at 'Std2_BB-filteredsorted.qname_sorted.bam.bai**

Yet the bam files I previously input (into pe.bams) were not bai files, but just the bam alignment files. Am I missing a step or should I have input .bai files instead? Should I perform some transformation on the inputs to regionCounts before running the function? Everything works perfectly (establishing the GRanges objects, etc) up until this point.

Any help or advice would be appreciated!

**Comment by rrashford** [comment]
An update on this issue--

I was able to generate a .bai file for each of my .bam files using samtools. Yet when I try to run the regionCounts function again on either the .bam or the .bai, I get a different error:
```
Error in value[[3L]](cond) : 
  failed to open BamFile: failed to open SAM/BAM file
  file: 'sample1_filteredSortedCoord_index.bai'
```

So I ran **traceback()** to see where it failed and don't understand what I should change based on this output!
```
> traceback()
14: stop("failed to open BamFile: ", conditionMessage(err))
13: value[[3L]](cond)
12: tryCatchOne(expr, names, parentenv, handlers[[1L]])
11: tryCatchList(expr, classes, parentenv, handlers)
10: tryCatch({
        .io_check_exists(path(con))
        index <- sub("\\.bai$", "", index(con, asNA = FALSE))
        con$.extptr <- .Call(.bamfile_open, path(con), index, "rb")
    }, error = function(err) {
        stop("failed to open BamFile: ", conditionMessage(err))
    })
9: open.BamFile(BamFile(file, character(0)))
8: open(BamFile(file, character(0)))
7: FUN(X[[i]], ...)
6: lapply(files, function(file) {
       bam <- open(BamFile(file, character(0)))
       on.exit(close(bam))
       scanBamHeader(bam, ...)
   })
5: lapply(files, function(file) {
       bam <- open(BamFile(file, character(0)))
       on.exit(close(bam))
       scanBamHeader(bam, ...)
   })
4: scanBamHeader(bam)
3: scanBamHeader(bam)
2: .activeChrs(bam.files, param$restrict)
1: regionCounts(pe.bams, all.peaks, param = param)
```

**Comment by reskejak** [comment]
So sorry for the delayed response! I am just seeing this.

Try running `samtools index sample1_filteredSortedCoord_index.bam` and it should create an indexed file `sample1_filteredSortedCoord_index.bam.bai`. Both the *.bam and *.bam.bai files will be needed for csaw to count reads.

**Comment by reskejak** [comment]
So sorry for the delayed response! My apologies, as I am just now seeing this.

You should specify the *.bam file to csaw, and it will automatically detect the corresponding *.bam.bai file provided that they have the same name. I think. I have a hunch that you need to have the files labeled as *.bam and *.bam.bai, rather than *.bai. Maybe that is the issue? Or vice versa, as the traceback appears to be searching for *.bai.

Feel free to respond or contact via email if you're still working on this problem (reskejak@msu.edu). Would appreciate if you provide any solutions or closure you were able to do so, too. Thanks!

**Comment by rrashford** [comment]
Yes, I got this to work by having my files named *.bam! and then csaw automatically detected the corresponding .bai. Thank you so much!

**Comment by reskejak** [comment]
Great to hear!
