### ISSUE TITLE
Error with bedpeMinimalConvert.sh file not recognizing .tn5.bedpe file from previous step

### ISSUE THREAD

**Issue by kimmaip** [reskejak/ATAC-seq#6]
Hi,

I'm following your workflow and I'm curious where my error is from.

Below is the input and output of the step # Minimal conversion (from standard BEDPE format to that accepted by MACS2) in my linux terminal.

(bio) [kphan4@gpu1 resmet]$ bash bedpeMinimalConvert.sh ./A1/A1_sub.tn5.bedpe > ./A1/A1_sub.minimal.bedpe
bedpeMinimalConvert.sh: line 40: coords../A1/A1_sub.tn5.bedpe: No such file or directory
bedpeMinimalConvert.sh: line 23: coords../A1/A1_sub.tn5.bedpe: No such file or directory
rm: cannot remove 'coords../A1/A1_sub.tn5.bedpe': No such file or directory

There is still a sub.minimal.bedpe file that gets saved, but I'm unsure if it is a complete file since these errors regarding the coords referenced from the tn5.bedpe file couldn't be found.

Any advice on this would be greatly appreciated!

**Comment by reskejak** [comment]
Hi Kimmai,

I think bash is having a hard time following your paths listed. I have a hunch that if you were to navigate into the folder A1 then run `bash bedpeMinimalConvert.sh A1_sub.tn5.bedpe > A1_sub.minimal.bedpe`, it should work properly.

Best,
Jake

**Comment by kimmaip** [comment]
Hi Jake,

Thanks for the advice! I ultimately did navigate into the folder and made sure the bash script was in the same folder as the file I was trying to convert and I was operating in the same directory where all these items were located. 

-Kimmai
