### ISSUE TITLE
Differentially accessible peaks in fasta file

### ISSUE THREAD

**Issue by beroult** [reskejak/ATAC-seq#9]
Hello,

Thanks for the great pipeline. Can you please share if you know how to transform the differentially accessible peaks in fasta file format so to access the sequences of differentially accessible peaks?

Kind regards,
Beri

**Comment by reskejak** [comment]
The best way to do this would be to use the BED file coordinates for each peak and align them with the `genome.fasta` file. It looks like the following R package can do this: https://rdrr.io/cran/hoardeR/man/getFastaFromBed.html

Best, Jake

**Comment by beroult** [comment]
Many thanks for the suggestion! It works well.
Kind regards,
Beri
